app = 'quanlykho-wecamp'
primary_region = 'sin'

[build]
  # Không cần buildpacks vì dùng Dockerfile
  # Fly tự dùng Dockerfile nếu có

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # Giữ máy chạy liên tục (không ngủ)
  auto_start_machines = true
  min_machines_running = 1     # Luôn có ít nhất 1 máy chạy (tránh cold start)

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'