# Generated by Django 4.2.27 on 2025-12-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongThuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=200, unique=True, verbose_name='Tên món')),
            ],
            options={
                'verbose_name_plural': '2. Công thức món',
            },
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, unique=True, verbose_name='Tên hàng hóa')),
                ('don_vi_quay_bar', models.CharField(max_length=50, verbose_name='Đơn vị quầy bar (ml, g, kg…)')),
                ('don_vi_le_tan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị lễ tân (chai, lon…)')),
                ('ty_le_quy_doi', models.DecimalField(decimal_places=4, default=1.0, help_text='Ví dụ: 1 chai Coca = 1500ml → nhập 1500.0000', max_digits=12, verbose_name='1 đơn vị lễ tân = bao nhiêu quầy bar?')),
            ],
            options={
                'verbose_name_plural': '1. Hàng hóa',
            },
        ),
        migrations.CreateModel(
            name='XuatMonFabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField(verbose_name='Ngày xuất')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng món')),
                ('cong_thuc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.congthuc')),
            ],
            options={
                'verbose_name_plural': '6. Xuất món theo Fabi (Excel)',
            },
        ),
        migrations.CreateModel(
            name='XuatNguyenLieuFabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField(verbose_name='Ngày xuất')),
                ('so_luong', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Số lượng theo Fabi')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '7. Xuất nguyên liệu theo Fabi (tự động)',
                'unique_together': {('ngay_xuat', 'hang_hoa')},
            },
        ),
        migrations.CreateModel(
            name='TonKhoQuayBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('ton_dau', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14, verbose_name='Tồn đầu ngày (tự động)')),
                ('nhap', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Nhập trong ngày')),
                ('ton_cuoi', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Tồn cuối ngày (nhân viên nhập)')),
                ('luong_dung', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14, verbose_name='Lượng dùng trong ngày (tự động)')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_quay_bar', to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '3. Tồn kho quầy bar',
                'unique_together': {('hang_hoa', 'ngay')},
            },
        ),
        migrations.CreateModel(
            name='TonKhoLeTan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('ton_cuoi', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Tồn cuối ngày (nhân viên nhập)')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_le_tan', to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '4. Tồn kho lễ tân',
                'unique_together': {('hang_hoa', 'ngay')},
            },
        ),
        migrations.CreateModel(
            name='TongTonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('ton_quay_bar', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14, verbose_name='Tồn quầy bar')),
                ('ton_le_tan', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14, verbose_name='Tồn lễ tân')),
                ('tong_quy_doi', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14, verbose_name='TỔNG TỒN (quy đổi về quầy bar)')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '5. Tổng tồn kho (tự động)',
                'unique_together': {('hang_hoa', 'ngay')},
            },
        ),
        migrations.CreateModel(
            name='TongLuongDungQuayBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField(verbose_name='Từ ngày')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Đến ngày')),
                ('tong_luong_dung', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='TỔNG LƯỢNG DÙNG (thực tế quầy bar)')),
                ('so_ngay', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số ngày')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '9. Tổng lượng dùng quầy bar theo khoảng ngày',
                'indexes': [models.Index(fields=['ngay_bat_dau', 'ngay_ket_thuc'], name='inventory_t_ngay_ba_a9ff54_idx')],
                'unique_together': {('hang_hoa', 'ngay_bat_dau', 'ngay_ket_thuc')},
            },
        ),
        migrations.CreateModel(
            name='SoSanhFabiVsThucTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField(verbose_name='Từ ngày')),
                ('ngay_ket_thuc', models.DateField(verbose_name='Đến ngày')),
                ('fabi_tong', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='Tổng Fabi (lý thuyết)')),
                ('thuc_te_tong', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='Tổng thực tế (quầy bar)')),
                ('chenh_lech_tong', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='Chênh lệch tổng kỳ')),
                ('ghi_chu', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Kết luận')),
                ('so_ngay', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số ngày')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '8. SO SÁNH FABI VS THỰC TẾ THEO KỲ (CHÍNH THỨC)',
                'indexes': [models.Index(fields=['ngay_bat_dau', 'ngay_ket_thuc'], name='inventory_s_ngay_ba_6dc698_idx')],
                'unique_together': {('hang_hoa', 'ngay_bat_dau', 'ngay_ket_thuc')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietCongThuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinh_luong', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Định lượng cho 1 món')),
                ('cong_thuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.congthuc')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hanghoa')),
            ],
            options={
                'verbose_name_plural': '   Chi tiết công thức',
                'unique_together': {('cong_thuc', 'hang_hoa')},
            },
        ),
    ]
