# Generated by Django 4.2.27 on 2025-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanghoa',
            options={'ordering': ['loai', 'ten'], 'verbose_name_plural': '1. Hàng hóa'},
        ),
        migrations.AddField(
            model_name='hanghoa',
            name='loai',
            field=models.CharField(choices=[('nuoc_uong', 'Nước uống'), ('do_an', 'Đồ ăn'), ('khac', 'Khác')], default='nuoc_uong', max_length=20, verbose_name='Phân loại'),
        ),
    ]
